### ISSUE TITLE
Schema

### ISSUE THREAD

**Issue by samih-sghier** [kava-market/kava-api#1]
```
User1: 
    uniqueUserId:
    schoolName:
    email: 
    phone: 
    items: 
         item1: 
              uniqueItemId: 
              title: 
              price: 
              type: 
              description: 
              imageUrl: 
         item2: 
         item3: 
User2:
```
userId generated by third party api on verification?.
